// Generated by scripts/gen-types.ts from vendor/jotted/schema.json. Do not edit.
// Release 0.1.0, contract 1 (accepts 1+).

export const RELEASE = "0.1.0";
export const CONTRACT = 1;

export type ErrorCode = "busy" | "config" | "conflict" | "internal" | "interrupted" | "invalid" | "model_error" | "not_connected" | "not_found" | "not_set_up" | "usage";

export const COMMANDS = [
  "setup",
  "setup status",
  "setup prepare",
  "ai",
  "ai key",
  "ai remove",
  "ai provider",
  "ai model",
  "plugins",
  "items",
  "items list",
  "items get",
  "items add",
  "items add-batch",
  "items accept",
  "items edit",
  "items done",
  "items reopen",
  "items dismiss",
  "library",
  "watch",
  "settings",
  "settings set",
  "collect",
  "todo",
  "check",
  "status",
  "image page",
  "image line",
  "events",
  "serve",
  "start",
  "update",
  "version",
  "schema",
  "mcp",
  "claude connect",
  "claude status",
  "claude disconnect",
  "config check",
  "connect",
  "auth",
] as const;
export type CommandName = (typeof COMMANDS)[number];

/** Each command's `data`, by command name. */
export interface Data {
  /** set-up steps: status, prepare; alone, the interactive walkthrough */
  "setup": unknown;
  /** every setup step, done or not, and the command that does it */
  "setup status": {
    complete: boolean;
    steps: {
      command?: string;
      detail?: string;
      done: boolean;
      id: string;
      optional?: boolean;
      title: string;
    }[];
  };
  /** the steps that need no answer: the app folder, the source's tools */
  "setup prepare": {
    complete: boolean;
    prepared: {
      detail: string | null;
      id: string;
    }[];
    steps: {
      command?: string;
      detail?: string;
      done: boolean;
      id: string;
      optional?: boolean;
      title: string;
    }[];
  };
  /** the language model and the Jev plugin: status, keys, provider, model */
  "ai": {
    jev: {
      by: string;
      enabled: boolean;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      model: string;
      name: string;
    };
    judge: "llm" | "jev";
    llm: {
      family: string;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      label: string;
      model: string;
      provider: string;
      providers: {
        id: string;
        label: string;
      }[];
    };
  };
  /** check and save a key (adding Jev's turns the plugin on) */
  "ai key": {
    jev: {
      by: string;
      enabled: boolean;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      model: string;
      name: string;
    };
    judge: "llm" | "jev";
    llm: {
      family: string;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      label: string;
      model: string;
      provider: string;
      providers: {
        id: string;
        label: string;
      }[];
    };
  };
  /** turn the Jev plugin off */
  "ai remove": {
    jev: {
      by: string;
      enabled: boolean;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      model: string;
      name: string;
    };
    judge: "llm" | "jev";
    llm: {
      family: string;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      label: string;
      model: string;
      provider: string;
      providers: {
        id: string;
        label: string;
      }[];
    };
  };
  /** choose the LLM adapter (anthropic) */
  "ai provider": {
    jev: {
      by: string;
      enabled: boolean;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      model: string;
      name: string;
    };
    judge: "llm" | "jev";
    llm: {
      family: string;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      label: string;
      model: string;
      provider: string;
      providers: {
        id: string;
        label: string;
      }[];
    };
  };
  /** choose the model; it has to read images */
  "ai model": {
    jev: {
      by: string;
      enabled: boolean;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      model: string;
      name: string;
    };
    judge: "llm" | "jev";
    llm: {
      family: string;
      key: {
        hint: string | null;
        set: boolean;
        source: "saved" | "environment" | null;
      };
      key_url: string;
      label: string;
      model: string;
      provider: string;
      providers: {
        id: string;
        label: string;
      }[];
    };
  };
  /** installed source plugins, and which one is chosen */
  "plugins": {
    chosen: string | null;
    installed: {
      chosen: boolean;
      label?: string;
      module: string;
      name: string;
    }[];
  };
  /** the to-do list: list, add, propose, accept, edit, tick, dismiss */
  "items": {
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  }[];
  /** list items (the default) */
  "items list": {
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  }[];
  /** one item, in any status, with where it came from */
  "items get": {
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  };
  /** add an item (once per --source-key) */
  "items add": {
    created: boolean;
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  };
  /** add up to 100 items from a JSON array on standard input */
  "items add-batch": {
    results: {
      error?: {
        code: string;
        message: string;
      };
      id?: number;
      index: number;
      outcome: "created" | "existing" | "dismissed" | "invalid" | "conflict" | "internal";
    }[];
  };
  /** put proposed items on the list */
  "items accept": {
    accepted: number[];
    skipped: {
      id: number;
      reason: "not_found" | "not_proposed";
    }[];
  };
  /** change an item's text or owner */
  "items edit": {
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  };
  /** mark an item done */
  "items done": {
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  };
  /** mark an item open again */
  "items reopen": {
    created_at: string;
    edited: boolean;
    id: number;
    origin: string;
    owner: "me" | "someone_else" | "unclear";
    owner_name: string | null;
    p_action: number;
    page: null | {
      anchor: string;
      doc_id: string;
      doc_name: string;
      page: number;
      page_count: number | null;
    };
    paper_text: string;
    slot: number | null;
    source: {
      anchor: string;
      doc_id: string;
      excerpt: string | null;
      folder: string;
      key: string | null;
      kind: string | null;
      name: string;
      page: number;
      title: string | null;
      url: string | null;
    };
    status: "open" | "done" | "proposed" | "dismissed";
    text: string;
    written: boolean;
  };
  /** not an action, or not wanted: take it off the list; its source never adds it again */
  "items dismiss": Record<string, unknown>;
  /** list your device's folders and which are watched */
  "library": {
    documents: {
      baseline_pages: number;
      folder: string;
      id: string;
      own: boolean;
      path: string;
      read: boolean;
      watched: boolean;
    }[];
    folders: {
      documents: number;
      path: string;
      watched: boolean;
    }[];
  };
  /** watch or stop watching a folder (also in the web app) */
  "watch": {
    action_threshold: number;
    from_now: string[];
    include_others: boolean;
    mcp_add_mode: "auto" | "propose_all";
    poll_interval_s: number;
    proposed_limit: number;
    todo_enabled: boolean;
    todo_folder: string;
    todo_name: string;
    watch: string[];
  } | {
    already_read: string[];
    documents: string[];
    settings: {
      action_threshold: number;
      from_now: string[];
      include_others: boolean;
      mcp_add_mode: "auto" | "propose_all";
      poll_interval_s: number;
      proposed_limit: number;
      todo_enabled: boolean;
      todo_folder: string;
      todo_name: string;
      watch: string[];
    };
  };
  /** show or change settings (also in the web app) */
  "settings": {
    action_threshold: number;
    from_now: string[];
    include_others: boolean;
    mcp_add_mode: "auto" | "propose_all";
    poll_interval_s: number;
    proposed_limit: number;
    todo_enabled: boolean;
    todo_folder: string;
    todo_name: string;
    watch: string[];
  };
  /** set one: e.g. todo_enabled true, action_threshold 0.8 */
  "settings set": {
    action_threshold: number;
    from_now: string[];
    include_others: boolean;
    mcp_add_mode: "auto" | "propose_all";
    poll_interval_s: number;
    proposed_limit: number;
    todo_enabled: boolean;
    todo_folder: string;
    todo_name: string;
    watch: string[];
  };
  /** read what changed in watched folders and update the to-do list */
  "collect": {
    actions_missing: number;
    actions_new: number;
    actions_updated: number;
    docs_changed: number;
    docs_seen: number;
    errors: string[];
    lines_judged: number;
    pages_baselined: number;
    pages_read: number;
    pages_skipped: number;
  } | {
    id: string;
    pages: number[];
    path: string;
  }[];
  /** read ticks from, and republish, the To-do document */
  "todo": {
    enabled?: boolean;
  };
  /** collect and update the To-do document now */
  "check": {
    collect?: unknown;
    todo?: unknown;
  };
  /** what Jotted reads, judges and publishes, and when it last did */
  "status": {
    background: unknown;
    documents_read: number;
    items: {
      done: number;
      open: number;
      proposed: number;
    };
    judge: string;
    last_collected_at: string | null;
    source: {
      connected: boolean;
      detail: string;
      device: string;
      label: string;
      mark: string;
      name: string;
    };
    todo: {
      enabled: boolean;
      folder: string;
      name: string;
      published_at: string | null;
    };
    watch: string[];
  };
  /** a page, with a line highlighted */
  "image page": {
    svg: string;
  } | {
    path: string;
  };
  /** one handwritten line */
  "image line": {
    svg: string;
  } | {
    path: string;
  };
  /** changes since a cursor; --follow keeps printing them */
  "events": {
    cursor: number;
    events: {
      at: string;
      cursor: number;
      type: "item.added" | "item.changed" | "item.removed" | "item.proposed" | "item.accepted" | "check.started" | "check.finished" | "todo.published" | "settings.changed" | "source.error";
    }[];
  };
  /** run the web app, background checking and the CLI's fast path */
  "serve": unknown;
  /** set up anything missing, then open the app (start here) */
  "start": unknown;
  /** update Jotted to the latest version on GitHub */
  "update": {
    updated: boolean;
  };
  /** release and contract versions */
  "version": {
    bundled: boolean;
    contract: number;
    contract_min: number;
    python: string;
    source_plugin: string | null;
    version: string;
  };
  /** every command: its arguments, options and the shape of its data */
  "schema": Record<string, unknown>;
  /** serve Jotted's operations as MCP tools on stdio (for agents) */
  "mcp": unknown;
  /** add Jotted to Claude Desktop's MCP servers (backs up its settings first) */
  "claude connect": {
    backup_path: string | null;
    changed: boolean;
    config_path: string;
    dry_run?: boolean;
    entry?: Record<string, unknown>;
    restart_required: boolean;
  };
  /** whether Claude Desktop runs Jotted, and whether that copy still exists */
  "claude status": {
    admin: boolean;
    command: string | null;
    command_exists: boolean;
    config_path: string;
    configured: boolean;
    env: Record<string, unknown>;
    installed: boolean;
    matches_current: boolean;
  };
  /** remove Jotted from Claude Desktop's MCP servers (backs up first) */
  "claude disconnect": {
    backup_path: string | null;
    changed: boolean;
    config_path: string;
    dry_run?: boolean;
    entry?: Record<string, unknown>;
    restart_required: boolean;
  };
  /** validate config.toml and print resolved values */
  "config check": {
    ai: {
      jev: {
        by: string;
        enabled: boolean;
        key: {
          hint: string | null;
          set: boolean;
          source: "saved" | "environment" | null;
        };
        key_url: string;
        model: string;
        name: string;
      };
      judge: "llm" | "jev";
      llm: {
        family: string;
        key: {
          hint: string | null;
          set: boolean;
          source: "saved" | "environment" | null;
        };
        key_url: string;
        label: string;
        model: string;
        provider: string;
        providers: {
          id: string;
          label: string;
        }[];
      };
    };
    config: Record<string, unknown>;
    path: string;
    source: {
      connected: boolean;
      detail: string;
      device: string;
      label: string;
      mark: string;
      name: string;
    };
  };
  /** connect your reMarkable with a one-time code */
  "connect": {
    connected: boolean;
    documents?: number;
    replaced?: boolean;
  };
  /** Get a one-time code at https://my.remarkable.com/device/desktop/connect (sign in, then connect a desktop app). */
  "auth": {
    connected: boolean;
    documents?: number;
    replaced?: boolean;
  };
}

export type Item = Data["items"][number];
export type ItemSource = Item["source"];
export type Owner = Item["owner"];
export type Settings = Data["settings"];
export type Status = Data["status"];
export type Ai = Data["ai"];
export type Version = Data["version"];
export type SetupStatus = Data["setup status"];
export type SetupStep = SetupStatus["steps"][number];
export type Library = Data["library"];
export type EventsPage = Data["events"];
export type EventType = EventsPage["events"][number]["type"];
