// vendor/jotted/schema.json → src/jotted/types.gen.ts
//
// Every command's `data` shape becomes a TypeScript type, keyed by the command's name.
// Run after bumping the pin (fetch-jotted runs it for you): `npm run gen-types`.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA = join(root, "vendor/jotted/schema.json");
const OUT = join(root, "src/jotted/types.gen.ts");

type JsonSchema = {
  type?: string | string[];
  enum?: (string | number | boolean | null)[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  oneOf?: JsonSchema[];
  description?: string;
};

type Command = { command: string; help: string; data: JsonSchema };

const PRIMITIVES: Record<string, string> = {
  string: "string",
  integer: "number",
  number: "number",
  boolean: "boolean",
  null: "null",
};

function pad(depth: number): string {
  return "  ".repeat(depth);
}

export function toTs(s: JsonSchema, depth = 0): string {
  if (s.oneOf) return s.oneOf.map((o) => toTs(o, depth)).join(" | ");
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  const types = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  if (types.length > 1) return types.map((t) => toTs({ ...s, type: t }, depth)).join(" | ");
  const [type] = types;
  if (type === "array") {
    const inner = s.items ? toTs(s.items, depth) : "unknown";
    return /[|&]/.test(inner) && !inner.trimStart().startsWith("{") ? `(${inner})[]` : `${inner}[]`;
  }
  if (type === "object" || s.properties) {
    const required = new Set(s.required ?? []);
    const props = Object.entries(s.properties ?? {}).map(
      ([key, value]) => `${pad(depth + 1)}${key}${required.has(key) ? "" : "?"}: ${toTs(value, depth + 1)};`,
    );
    return props.length ? `{\n${props.join("\n")}\n${pad(depth)}}` : "Record<string, unknown>";
  }
  if (type && PRIMITIVES[type]) return PRIMITIVES[type];
  return "unknown"; // `{}` or a description only: the CLI doesn't promise a shape
}

export function generate(schema: {
  version: string;
  contract: number;
  contract_min: number;
  commands: Command[];
  errors: Record<string, unknown>;
}): string {
  const lines = [
    `// Generated by scripts/gen-types.ts from vendor/jotted/schema.json. Do not edit.`,
    `// Release ${schema.version}, contract ${schema.contract} (accepts ${schema.contract_min}+).`,
    ``,
    `export const RELEASE = ${JSON.stringify(schema.version)};`,
    `export const CONTRACT = ${schema.contract};`,
    ``,
    `export type ErrorCode = ${Object.keys(schema.errors).map((c) => JSON.stringify(c)).join(" | ")};`,
    ``,
    `export const COMMANDS = [`,
    ...schema.commands.map((c) => `  ${JSON.stringify(c.command)},`),
    `] as const;`,
    `export type CommandName = (typeof COMMANDS)[number];`,
    ``,
    `/** Each command's \`data\`, by command name. */`,
    `export interface Data {`,
    ...schema.commands.map((c) => `  /** ${c.help} */\n  ${JSON.stringify(c.command)}: ${toTs(c.data, 1)};`),
    `}`,
    ``,
    `export type Item = Data["items"][number];`,
    `export type ItemSource = Item["source"];`,
    `export type Owner = Item["owner"];`,
    `export type Settings = Data["settings"];`,
    `export type Status = Data["status"];`,
    `export type Ai = Data["ai"];`,
    `export type Version = Data["version"];`,
    `export type SetupStatus = Data["setup status"];`,
    `export type SetupStep = SetupStatus["steps"][number];`,
    `export type Library = Data["library"];`,
    `export type EventsPage = Data["events"];`,
    `export type EventType = EventsPage["events"][number]["type"];`,
    ``,
  ];
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const schema = JSON.parse(readFileSync(SCHEMA, "utf8"));
  writeFileSync(OUT, generate(schema));
  console.log(`wrote ${OUT.replace(root + "/", "")} (release ${schema.version}, contract ${schema.contract})`);
}
